export const ADD_LOGIN="ADD_LOGIN";

export const ADD_MATCHES="ADD_MATCHES";
export const ADD_USERS="ADD_USERS";

export const USERS_LOADING="USERS_LOADING";


export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';

export const LEADERS_LOADING = 'LEADERS_LOADING';
export const ADD_LEADERS = 'ADD_LEADERS';
export const PROMOS_LEADERS = 'PROMOS_LEADERS';
export const LEADERS_FAILED = 'LEADERS_FAILED';

